apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: e-commerce
build:
  artifacts:
    - image: gateway-api
      context: gateway-api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "**/*"
            src: .
    - image: user-service
      context: user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "**/*"
            src: .
    - image: product-service
      context: product-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "**/*"
            src: .
    - image: inventory-service
      context: inventory-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "**/*"
            src: .
    - image: order-service
      context: order-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: "**/*"
            src: .
manifests:
  rawYaml:
    - k8s/*.yml
portForward:
  - resourceType: deployment
    resourceName: gateway-depl
    namespace: default
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: rabbitmq-srv
    namespace: default
    port: 15672
    localPort: 15672
