apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: cart-service
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: CART_SERVICE_GRPC_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CART_SERVICE_GRPC_ADDR
            - name: DB_CONNECTION_LINK
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_CONNECTION_LINK
            - name: CART_SERVICE_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CART_SERVICE_DATABASE_NAME
            - name: CART_SERVICE_DATABASE_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CART_SERVICE_DATABASE_COLLECTION
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - name: grpc
      protocol: TCP
      port: 3003
      targetPort: 3003
