apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway-api
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: GATEWAY_API_HTTP_ADRR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GATEWAY_API_HTTP_ADRR
            - name: GATEWAY_API_USER_SERVICE_GRPC_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GATEWAY_API_USER_SERVICE_GRPC_ADDR
            - name: GATEWAY_API_PRODUCT_SERVICE_GRPC_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GATEWAY_API_PRODUCT_SERVICE_GRPC_ADDR
            - name: GATEWAY_API_INVENTORY_SERVICE_GRPC_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GATEWAY_API_INVENTORY_SERVICE_GRPC_ADDR
            - name: GATEWAY_API_ORDER_SERVICE_GRPC_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GATEWAY_API_ORDER_SERVICE_GRPC_ADDR
            - name: GATEWAY_API_PAYMENT_SERVICE_GRPC_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GATEWAY_API_PAYMENT_SERVICE_GRPC_ADDR
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-srv
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
