apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: inventory-service
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: INVENTORY_SERVICE_GRPC_ADDR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_GRPC_ADDR
            - name: DB_CONNECTION_LINK
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_CONNECTION_LINK
            - name: INVENTORY_SERVICE_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_DATABASE_NAME
            - name: INVENTORY_SERVICE_DATABASE_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_DATABASE_COLLECTION
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-srv
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - name: grpc
      protocol: TCP
      port: 3003
      targetPort: 3003
